[project]
name = "zombiotrack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.1",
    "typer>=0.15.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]

