name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync Dependencies
        run: uv sync --group default --group test

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v1
        with:
          args: check .

      - name: Run Tests with pytest
        run: uv run pytest --maxfail=1 --disable-warnings -q
